import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Menu from '../components/Menu';
import MyMap from '../components/MyMap';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Menu />
        <h1 className={styles.title}>
          <Link href="/">
            <a>Reunion hokus pokus...</a>
          </Link>
        </h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            <Link href="/mapa">
              <a>
                <h2>Mapa &rarr;</h2>
                <p>Find in-depth information about Next.js features and API.</p>
              </a>
            </Link>
          </div>

          <div className={styles.card}>
            <Link href="/vylety">
              <a>
                <h2>Výlety &rarr;</h2>
                <p>Find in-depth information about Next.js features and API.</p>
              </a>
            </Link>
          </div>

          <div className={styles.card}>
            <Link href="/galerie">
              <a>
                <h2>Galerie &rarr;</h2>
                <p>Find in-depth information about Next.js features and API.</p>
              </a>
            </Link>
          </div>

          <div className={styles.card}>
            <Link href="/kontakt">
              <a>
                <h2>Kontakt &rarr;</h2>
                <p>Find in-depth information about Next.js features and API.</p>
              </a>
            </Link>
          </div>
        </div>
        <MyMap />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
